AppVersion: v0

Tokens:
  Server:


Gin:
  Mode: release


Grpc:
  Host:
  Port: 5555
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5


Http:
  Host:
  Port: 8080
  PprofPort: ":8100"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"


Kafka:
  Brokers:

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Jaeger:
  Host: localhost
  Port: 9411
  ServiceName: accounts_microservice
  LogSpans: false

MongoDB:
  URI: mongodb://localhost:27017
  User:
  Password:
  DB:
MysqlDB:
  Host:
  Port:
  Username:
  Password:
  DB:
  Mode: debug
  LogLevel: 4


Redis:
  Host:
  Port: 3306
  RedisPassword:
  RedisDb: 0
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password:
  DB: 0

Firebase:
  KeyPath:
  ProjectID: